# Generated by Django 4.1.3 on 2022-11-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_done_task_task_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task_done', '-datetime']},
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
    ]
