# Generated by Django 4.1.3 on 2022-11-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_options_alter_task_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-task_done', '-created_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
